<?php
/**
 * Dynamic Robots.txt Generator
 * Tro365 - Website thuê trọ
 */

// Simple robots.txt without complex dependencies
$baseUrl = 'http://localhost:8000';

// Set content type
header('Content-Type: text/plain; charset=utf-8');

$isMaintenanceMode = false; // Simplified for now

if ($isMaintenanceMode) {
    // Block all crawlers during maintenance
    echo "User-agent: *\n";
    echo "Disallow: /\n";
} else {
    // Normal robots.txt
    echo "User-agent: *\n";
    echo "Allow: /\n";
    echo "\n";
    
    // Disallow admin and private areas
    echo "Disallow: /admin/\n";
    echo "Disallow: /api/\n";
    echo "Disallow: /includes/\n";
    echo "Disallow: /config/\n";
    echo "Disallow: /classes/\n";
    echo "Disallow: /vendor/\n";
    echo "Disallow: /uploads/temp/\n";
    echo "Disallow: /assets/temp/\n";
    echo "\n";
    
    // Disallow search with parameters
    echo "Disallow: /search?*\n";
    echo "Disallow: /*?page=*\n";
    echo "Disallow: /*?sort=*\n";
    echo "\n";
    
    // Allow specific areas
    echo "Allow: /assets/\n";
    echo "Allow: /uploads/posts/\n";
    echo "Allow: /uploads/avatars/\n";
    echo "\n";
    
    // Sitemap location
    echo "Sitemap: " . rtrim($baseUrl, '/') . "/sitemap.php\n";
    
    echo "\n";
    
    // Crawl delay for different bots
    echo "User-agent: Googlebot\n";
    echo "Crawl-delay: 1\n";
    echo "\n";
    
    echo "User-agent: Bingbot\n";
    echo "Crawl-delay: 2\n";
    echo "\n";
    
    echo "User-agent: *\n";
    echo "Crawl-delay: 5\n";
}

echo "\n# Generated by Trọ 365 at " . date('Y-m-d H:i:s');
?>
